version: '2'
services:
    web:
        build: .
        restart: always
        ports:
            - "8000:8000"
        volumes:
            - ./app/.:/app
        depends_on:
            - redis
    redis:
        image: redis
        restart: always
